### ISSUE TITLE
Cannot read filter of undefined

### ISSUE THREAD

**Issue by tungi52** [neuronetio/angular-gantt-schedule-timeline-calendar#11]
In angular app if I navigate from a page which uses the timeline component I get the following error:

> TypeError: Cannot read property 'filter' of undefined
>     at index.esm.js:4881
>     at DeepState.getUpdateValues (index.esm.js:7960)
>     at DeepState.update (index.esm.js:8006)
>     at BindElementAction.destroy (index.esm.js:4880)
>     at vido.destroyComponent (index.esm.js:3265)
>     at PublicComponentMethods.destroy (index.esm.js:2766)
>     at index.esm.js:4804
>     at Array.forEach (<anonymous>)
>     at index.esm.js:4804
>     at InternalComponentMethods.destroy (index.esm.js:2890)
>     at resolvePromise (zone.js:852)
>     at resolvePromise (zone.js:809)
>     at zone.js:913
>     at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
>     at Object.onInvokeTask (core.js:26247)
>     at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:422)
>     at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:195)
>     at drainMicroTaskQueue (zone.js:601)
>     at ZoneTask.push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (zone.js:502)
>     at invokeTask (zone.js:1693)

After a small debugging I found out, that in the `onDestroy` function the first line sets `state.data` undefined, but in the `app.destroy` it would be necessary for some components.

```
this.state.destroy();
this.GSTC.app.destroy();
```

**Comment by qinxiaoxian** [comment]
Hello, I also have this problem. I refer to your description and find that it has no effect or reported an error. Can you describe it in more detail? Or post your code? Thank you.

**Comment by tungi52** [comment]
Take a look at this demo: [https://stackblitz.com/edit/angular-5gjxoz](https://stackblitz.com/edit/angular-5gjxoz)
The problem, is when I use angular routing, the navigation fails and only an empty page appears.

**Comment by pudelduscher** [comment]
a merge would be great

**Comment by SatchelCatral** [comment]
I'm having the same issue, hopefully the PR gets merged soon

**Comment by neuronetio** [comment]
should be fixed in newest version
