### ISSUE TITLE
[Feature] Access GTSC object or API

### ISSUE THREAD

**Issue by KyneSilverhide** [neuronetio/angular-gantt-schedule-timeline-calendar#13]
Hello,

I would like to be able to access the underlying API to call functions such as "scrollToTime". (ex using the base library https://github.com/neuronetio/gantt-schedule-timeline-calendar/blob/v3/dist/examples/period.html)

Unfortunately, I didn't find any solution to access these methods with Angular.

Best regards,

**Comment by MaloPolese** [comment]
> Hello,
> 
> I would like to be able to access the underlying API to call functions such as "scrollToTime". (ex using the base library https://github.com/neuronetio/gantt-schedule-timeline-calendar/blob/v3/dist/examples/period.html)
> 
> Unfortunately, I didn't find any solution to access these methods with Angular.
> 
> Best regards,

Hello,

I had the same problem,
I used a Viewchild to solve it.

`@ViewChild('gstc', { static: false }) gstc: GSTCComponent;`

Best regards

**Comment by KyneSilverhide** [comment]
Great, this works perfectly. I'll close the issue :)

**Comment by Phong95** [comment]
follow the answer i use like below:
this.gstc.GSTC.api.setPeriod();
i have error:
TypeError: Cannot read property 'GSTC' of undefined
how can you fix that @KyneSilverhide ?
Cheers,

**Comment by KyneSilverhide** [comment]
@Phong95  
In your component, you have to define 'hstc'

```
export class MyComponent implements OnInit {
...
@ViewChild('gstc', { static: false }) gstc!: GSTCComponent;

`ngOnInit(): void {`
..
}
```

**Comment by Phong95** [comment]
`
export class GanttScheduleComponent implements OnInit {

  @ViewChild('gstc', { static: false }) gstc: GSTCComponent;

  constructor(private obser: ObservableService) { }

  ngOnInit(): void {}

  changePeriod() {
    let inputValue = (document.getElementById('setperiod') as HTMLInputElement).value;
    const zoom = this.gstc.GSTC.api.setPeriod(inputValue);
  }
}
`
I already did that but the error still show:
ERROR TypeError: Cannot read property 'GSTC' of undefined
thanks for quick reply @KyneSilverhide

**Comment by KyneSilverhide** [comment]
@Phong95  You have to ensure that 'gstc' in @ViewChild('gstc'
matches the #name in your html.
Ex : `<gstc #gstc [config]="timelineConfig" (onState)="onState()"></gstc>`

Also, if <gstc ..> is somehow hidden (ngIf or switch), it won't be injected into the viewchild.

**Comment by Phong95** [comment]
thanks a lot @KyneSilverhide , i get api succeed but i cant find function setPeriod like example
