### ISSUE TITLE
Module not found when importing it

### ISSUE THREAD

**Issue by caiobozato** [neuronetio/angular-gantt-schedule-timeline-calendar#3]
Hello,

I'm importing the module using the guide provided in the repository, but I receive an error saying the module could not be found:

![image](https://user-images.githubusercontent.com/26546511/73549562-96a18a00-4421-11ea-8b82-54869abf4280.png)

I looked into `node_modules` folder, and found out that we don't have a file that exports the `angular-gantt-schedule-timeline-calendar` to be used:

![image](https://user-images.githubusercontent.com/26546511/73549664-c6e92880-4421-11ea-8de9-b42b3d592005.png)

If I use this full path, the module is found, but the building contains errors: 
`import { GSTCComponent } from 'angular-gantt-schedule-timeline-calendar/projects/angular-gantt-schedule-timeline-calendar/src/lib/angular-gantt-schedule-timeline-calendar.component';`

```
ERROR in ./node_modules/angular-gantt-schedule-timeline-calendar/projects/angular-gantt-schedule-timeline-calendar/src/lib/angular-gantt-schedule-timeline-calendar.component.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: /Users/caiobozatoaroca/Documents/Projects/pocs/vplanner/node_modules/angular-gantt-schedule-timeline-calendar/projects/angular-gantt-schedule-timeline-calendar/src/lib/angular-gantt-schedule-timeline-calendar.component.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/Users/caiobozatoaroca/Documents/Projects/pocs/vplanner/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:913:23)
    at /Users/caiobozatoaroca/Documents/Projects/pocs/vplanner/node_modules/@ngtools/webpack/src/loader.js:41:31
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

```

**Comment by neuronetio** [comment]
It should be ok now (v1.0.24)
Thanks for report!

**Comment by caiobozato** [comment]
Thanks a lot!
