### ISSUE TITLE
add item 

### ISSUE THREAD

**Issue by satya5561** [neuronetio/angular-gantt-schedule-timeline-calendar#5]
how to add row items dynamically in timeline. i have updated items in chart but not reflected in UI.

**Comment by neuronetio** [comment]
```
state.update('config.list.rows', rows => { 
  rows.push(row);
  return rows;
});
```

**Comment by satya5561** [comment]
> ```
> state.update('config.list.rows', rows => { 
>   rows.push(row);
>   return rows;
> });
> ```

thanks

**Comment by neuronetio** [comment]
sorry it was for rows not items :D
and rows config is not an array :D

first of all you should get the state from template `(onState)="onState($event)"`

and then in your component add method `onState(state){ this.gstcState = state; }`

later you can add item dynamically 
```
this.gstcState.update('config.chart.items', items=>{
  items[/* new item id */] = {/* item config */};
  return items;
})
```

**Comment by satya5561** [comment]
Using angular 6 i have implemented it my website but when i am navigate pages then got error 

`An error occurred: Uncaught (in promise): TypeError: Cannot read property 'filter' of undefined
TypeError: Cannot read property 'filter' of undefined
    at http://localhost:4200/vendor.js:137655:29
    at DeepState.getUpdateValues (http://localhost:4200/vendor.js:140704:24)
    at DeepState.update (http://localhost:4200/vendor.js:140750:45)
    at BindElementAction.destroy (http://localhost:4200/vendor.js:137653:20)
    at vido.destroyComponent (http://localhost:4200/vendor.js:136038:44)
    at PublicComponentMethods.destroy (http://localhost:4200/vendor.js:135539:38)
    at http://localhost:4200/vendor.js:137577:54
    at Array.forEach (<anonymous>)
    at http://localhost:4200/vendor.js:137577:21
    at InternalComponentMethods.destroy (http://localhost:4200/vendor.js:135663:17)`

after debugging  i have got the line code where this error comes .

line number 4879
node_modules/gantt-schedule-timeline-calendar/dist/index.esm.js
`destroy(element, data) {
        data.state.update('_internal.elements.list-columns', elements => {
            return elements.filter(el => el !== element);
        });
    }`
