### ISSUE TITLE
Help: update state via triggered function

### ISSUE THREAD

**Issue by caiobozato** [neuronetio/angular-gantt-schedule-timeline-calendar#6]
Hello,
I'm using `angular-gantt-schedule-timeline-calendar` and this example you provided: 
https://github.com/neuronetio/ng-gantt-schedule-timeline-calendar

My question is: I'm trying to create a function to update the `state` in order to change the Month view and want to trigger it from a button. 

If I put this on the state, the update occurs but on the beginning of the execution:

```
  onState(state) {
	this.gstcState = state;
	this.gstcState.update('config.chart.time.from', 1583031600000)
  }
}
```

But if I create a function with the same code, the state is not updated and I receive an error:

Function:
```
changeMonth(){
	this.gstcState.update('config.chart.time.from', 1583031600000)
  }
```

Error:
```
ERROR TypeError: this.gstcState.update is not a function
    at AppComponent.changeMonth (app.component.ts:19)
    at Object.eval [as handleEvent] (AppComponent.html:1)
    at handleEvent (core.js:43993)
    at callWithDebugContext (core.js:45632)
    at Object.debugHandleEvent [as handleEvent] (core.js:45247)
    at dispatchEvent (core.js:29804)
    at core.js:42925
    at HTMLButtonElement.<anonymous> (platform-browser.js:2668)
    at ZoneDelegate.invokeTask (zone-evergreen.js:391)
    at Object.onInvokeTask (core.js:39680)
```

I'm not able to access the `state` out of `onState` method in order to update it.

Thanks in advance!

**Comment by neuronetio** [comment]
For easy workaround you can just bind your function to current component but I will think of it later.
`[onState]="onState.bind(this)"`

**Comment by neuronetio** [comment]
From version 1.1.0 you should use `(onState)="onState($event)"`
