### ISSUE TITLE
Help: change schedule color

### ISSUE THREAD

**Issue by caiobozato** [neuronetio/angular-gantt-schedule-timeline-calendar#7]
Hello,

How do I change a scheduled time color?

Now I have all with same color: 

![image](https://user-images.githubusercontent.com/26546511/73869500-1ae07c80-4829-11ea-84cc-eae94d8d5c6b.png)

I want to change them depending on schedule type.

Thanks in advance

**Comment by neuronetio** [comment]
You can change style just but adding style property to item.
Like here: [gantt shedule timelie calendar example](https://github.com/neuronetio/gantt-schedule-timeline-calendar/blob/master/dist/examples/main.html#L97)

Another way is to create action and stylize elements dynamically but style property is easier of course.
