### ISSUE TITLE
can't trigger item action onClick

### ISSUE THREAD

**Issue by myelxx** [neuronetio/angular-gantt-schedule-timeline-calendar#9]
Hi, I'm new to this and I want to trigger onClick event once the item is click.

```
actions: {
          'chart-timeline-items-row-item': [this.addItem]
}

addItem(element, data){
    console.log(element)
}
```

Thank you

**Comment by neuronetio** [comment]
read [documentation](https://github.com/neuronetio/gantt-schedule-timeline-calendar)

**Comment by myelxx** [comment]
> read [documentation](https://github.com/neuronetio/gantt-schedule-timeline-calendar)

i'm a hard time integrating it on angular would like to give example?
